### ISSUE TITLE
Help to specify modification

### ISSUE THREAD

**Issue by pkl5** [PNNL-Comp-Mass-Spec/Informed-Proteomics#12]
I want to add some modifications to the mod.txt file. Can you point me to the guidance how to do that? e.g. what is the proper format of the text in the .txt file, and how do I specify the number of atoms for each element?

Thanks!

**Comment by alchemistmatt** [comment]
There are example modification definitions in the text files at https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/tree/master/Example_Files

The format of the file is 
EmpiricalFormula, AffectedResidue, ModType, PeptideLocation, ModName

* EmpiricalFormula is the elements to add or remove from the peptide
* AffectedResidue is the single letter amino acid abbrevation
* ModType is opt or fix, corresponding to a dynamic mod or a static mod
* PeptideLocation is any, N-term, C-Term, Prot-N-term, or Prot-C-term
* ModName is the name of the modification, preferably corresponding to a Unimod name (see the PSI-MS-Name and Interim Name columns at http://www.unimod.org/modifications_list.php?pagesize=200)

The file with a bunch of example mod definitions is https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/blob/master/Example_Files/Mod_Examples.txt

Note that the modification file format mirrors the one used by MS-GF+.  For additional information, see the comments at https://raw.githubusercontent.com/sangtaekim/msgfplus/master/doc/examples/Mods.txt
