### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by yousade** [PNNL-Comp-Mass-Spec/Informed-Proteomics#14]
Hi,

I am pretty sure I am doing something wrong, but I would like to know how to install Informed-Proteomics (and LCMS-Spectator) on Windows.

I have downloaded Informed-Proteomics-master and LCM-Spectator-master from GitHub, but I was not able to install both. I downloaded Inno Setup to compile .ISS files, but both installers gave me an error "The [Setup] section must include an AppVersion or AppVerName directive". These errors were corrected by removing a ; sign (line 98 for LCMS-Spectator, line 110 for Informed-Proteomics). Then when trying to compile again, another error shows about not finding a file at BIN folder (LcmsSpectator\bin\Release\LcmsSpectator.exe;). For Informed-Proteomics the error is about a .DLL not found again in the BIN folder. I think the problem is that there is no BIN folder in the .ZIP from GitHub. Could you help me to install these softwares? Thanks a lot.

**Comment by alchemistmatt** [comment]
You downloaded the source code; you need to instead download the installer.  Go to the Releases page (https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/releases) and download
`Informed-Proteomics_Installer.exe`

Alternatively, just download `MSPathFinder.zip` and extract the files.

**Comment by yousade** [comment]
Thanks a lot for your help!!
