### ISSUE TITLE
Create .mzid file if -tda 0

### ISSUE THREAD

**Issue by liv-acollins** [PNNL-Comp-Mass-Spec/Informed-Proteomics#2]
Currently does not create an .mzid file if -tda 0 is used. Can this be altered so that an .mzid file is always produced?

**Comment by FarmGeek4Life** [comment]
I have some changes in progress to always produce an .mzid file, but need to complete some other testing first...

**Comment by FarmGeek4Life** [comment]
The new [Latest Release](https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/releases/latest) of 1.0.6510 should take care of this issue.
