### ISSUE TITLE
Reported proteoform masses is always 9Da less

### ISSUE THREAD

**Issue by wingkinlui** [PNNL-Comp-Mass-Spec/Informed-Proteomics#22]
It occurs to me that the reported mass of the proteoforms are always ~9Da less than the mass calculated from the reported m/z and z.

In my knowledge, as I am using nESI as the ion source, the mass should be calculated as (m/z * z - z)

So as in the attached example,
for a precursor ion of 661m/z, charge = 23+, the mass should be 15180Da.
Yet, the reported proteoform mass was 15171.5.
The unmodified mass of my protein is 15143Da. Having K9Me1 and K27Me1, as MSpf reported, will make it 15171Da.

my search parameters are as follow:
'''
SpecFile	W05C48_H3_UVPD.raw
DatabaseFile	SOYBN_H3.fasta
FeatureFile	W05C48_H3_UVPD.ms1ft
InternalCleavageMode	NoInternalCleavage
Tag-based search	False
Tda	Target
PrecursorIonTolerancePpm	10
ProductIonTolerancePpm	10
MinSequenceLength	21
MaxSequenceLength	500
MinPrecursorIonCharge	2
MaxPrecursorIonCharge	50
MinProductIonCharge	1
MaxProductIonCharge	20
MinSequenceMass	3000
MaxSequenceMass	50000
ActivationMethod	Unknown
MaxDynamicModificationsPerSequence	5
Modification	C(0) H(0) N(0) O(1) S(0),M,opt,Everywhere,Oxidation
Modification	C(0) H(0) N(0) O(1) S(0),Y,opt,Everywhere,Oxidation
Modification	C(0) H(0) N(0) O(1) S(0),C,opt,Everywhere,Oxidation
Modification	C(0) H(0) N(0) O(1) S(0),K,opt,Everywhere,Oxidation
Modification	C(0) H(1) N(0) O(3) S(0) P(1),S,opt,Everywhere,Phospho
Modification	C(0) H(1) N(0) O(3) S(0) P(1),T,opt,Everywhere,Phospho
Modification	C(0) H(1) N(0) O(3) S(0) P(1),Y,opt,Everywhere,Phospho
Modification	C(2) H(2) N(0) O(1) S(0),K,opt,Everywhere,Acetyl
Modification	C(1) H(2) N(0) O(0) S(0),K,opt,Everywhere,Methyl
Modification	C(2) H(4) N(0) O(0) S(0),K,opt,Everywhere,Dimethyl
Modification	C(3) H(6) N(0) O(0) S(0),K,opt,Everywhere,Trimethyl
'''

![mass_error](https://user-images.githubusercontent.com/52278636/60255728-dd1a8d80-9902-11e9-9fd4-e48b4b08ab80.jpg)

**Comment by FarmGeek4Life** [comment]
Note that it is reporting the `Most Abundant Isotope m/z`, not the monoisotopic m/z; meanwhile the mass refers to the monoisotopic mass. The mass is not directly calculated using the most abundant isotope m/z, instead (if I remember correctly, and somebody may correct me on this) it uses an algorithm to take the whole isotopic distribution and determine what the monoisotopic mass of that distribution is.

I believe that averagine is used for part of this, and since all of those most abundant masses are in a relatively small range, the monoisotopic masses all end up with similar mass differences after adjusting for the atomic relative abundances.

**Comment by wingkinlui** [comment]
> Note that it is reporting the `Most Abundant Isotope m/z`, not the monoisotopic m/z; meanwhile the mass refers to the monoisotopic mass. The mass is not directly calculated using the most abundant isotope m/z, instead (if I remember correctly, and somebody may correct me on this) it uses an algorithm to take the whole isotopic distribution and determine what the monoisotopic mass of that distribution is.
> 
> I believe that averagine is used for part of this, and since all of those most abundant masses are in a relatively small range, the monoisotopic masses all end up with similar mass differences after adjusting for the atomic relative abundances.

Thank you so much for your reply.

But is it true that the monoisotopic species should still be inside of the isotopic envelope?
Using the same PrSM as an example, the calculated m/z from the reported proteoform's monoisotopic mass would be (15171.5+23)/23 = 660.63.
This m/z would be outside of the matched isotopic envelope.
And there is nothing detected in 660.63.
![660 63](https://user-images.githubusercontent.com/52278636/60392410-96ac7500-9b34-11e9-909e-0fa244294eca.png)
