### ISSUE TITLE
ProMex feature determination: Mass

### ISSUE THREAD

**Issue by wingkinlui** [PNNL-Comp-Mass-Spec/Informed-Proteomics#24]
Hi, I have a question about the feature mass determination in ProMex.

According to my understanding to the Informed-Proteomics publication,
(Park, J., Piehowski, P. D., Wilkins, C., Zhou, M., Mendoza, J., Fujimoto, G. M., Gibbons, B. C., Shaw, J. B., Shen, Y., Shukla, A. K., Moore, R. J., Liu, T., Petyuk, V. A., Tolić, N., Paša-Tolić, L., Smith, R. D., Payne, S. H., & Kim, S. (2017). Informed-Proteomics: Open-source software package for top-down proteomics. Nature Methods, 14(9), 909–914. https://doi.org/10.1038/nmeth.4388)
ProMex obtain features, by clustering isotopic envelopes across different charge states and LC elution time, for each monoisotopic mass with in mass range specified. So to my understanding, ProMex will iterate each possible monoisotopic mass within the mass range, and carry out the clustering to obtain feature information.

My question is, how refined is ProMex possible monoisotopic mass list? In my data, I noticed that ProMex could group near isobaric proteoforms, such as trimethylation VS acetylation, into the same feature, although they have slightly different monoisotopic mass.

I noticed that ProMex will divide the mass range into bins during analysis, and in the publication, it was said that a tolerance could be input in ProMex. So my guess is ProMex will divide the mass range into bins according to the tolerance, and then theoretical isotopic envelope will be generated for matching, using the averagine model of the bin mass. Therefore, for near isobaric proteoforms, their monoisotopic mass will fall into the same bin and will be grouped into the same feature with they co-elute.

Is my understanding correct?

**Comment by Jungkap** [comment]
Yes, you are correct.

**Comment by wingkinlui** [comment]
Thank you so much!
