### ISSUE TITLE
Is MSPathFinderT able to report isobaric proteoforms?

### ISSUE THREAD

**Issue by wingkinlui** [PNNL-Comp-Mass-Spec/Informed-Proteomics#25]
I have been using Informed-Proteomics to analysis Histone Top-down spectrums, and as you may already know, there are a lot of near-isobaric or isobaric proteoforms.

My question is, is MsPathFinderT able to report multiple proteoforms from a MS2 spectrum? According to my understanding to the Informed-Proteomics article and my application of this software, it would only report one best PrSM per one MS2 spectrum. In other words, if multiple (near-) isobaric proteoforms were co-isolated and co-fragmented in a MS2 scan, only the one with the best score will be reported.

Am I right about this?

**Comment by alchemistmatt** [comment]
NumMatchesPerSpectrum defaults to 3
https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/blob/8cfbdd4e33b7e228fd405808b70fe138666596c3/InformedProteomics.TopDown/Execution/MsPfParameters.cs#L66

So, it's keeping track of the top 3 matches per spectrum internally.  However, after running the generating function, it is only keeping the best match:
```C#
            foreach (var scanNum in scanNums)
            {
                finalMatches[scanNum] = matches[scanNum].OrderBy(m => m.SpecEvalue).First();
            }
```
https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/blob/8cfbdd4e33b7e228fd405808b70fe138666596c3/InformedProteomics.TopDown/Execution/IcTopDownLauncher.cs#L967

I should be able to update it to support writing multiple results per scan.

**Comment by wingkinlui** [comment]
I see. Thanks a lot!

**Comment by alchemistmatt** [comment]
The following commits implement the option of reporting multiple PSMs for each scan:
- 446117672aeb75436758e5a9e446fa83084b381e
- 565bb47e8f401528dc7130e5c39cfe4964681746
- ddc1a2463c7d2daa2b19b413de4bf729d79cdc99

See [Release 1.0.7569](https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/releases/tag/v1.0.7569)
