### ISSUE TITLE
Hex(2) treated as an unknown modification

### ISSUE THREAD

**Issue by liv-acollins** [PNNL-Comp-Mass-Spec/Informed-Proteomics#3]
Lactosylation / Hex(2) is treated as an unknown modification:
http://www.unimod.org/modifications_view.php?editid1=512

C12H20O10,RK,opt,any,Hex(2)     # Lactostylation

Current output:
`<SearchModification fixedMod="false" massDelta="324.105652" residues="R">
<cvParam cvRef="MS" accession="MS:1001460" name="unknown modification" value="Hex(2)" />
</SearchModification>`

Expected output:
`<SearchModification fixedMod="false" massDelta="324.105652" residues="R">
<cvParam cvRef="UNIMOD" accession="UNIMOD:512" name="Hex(2)" />
</SearchModification>`

**Comment by FarmGeek4Life** [comment]
This appears to be a name parsing issue. I need to update the library used to output the mzid file to properly handle the names when there is punctuation. For now, you should be able to get correct output in the mzid file by using "Hex_2_" instead of "Hex(2)"

**Comment by liv-acollins** [comment]
This also appears not to work:
`<Modification location="58" monoisotopicMassDelta="324.105647">
        <cvParam cvRef="MS" accession="MS:1001460" name="unknown modification" value="Hex_2_" />
      </Modification>`

`<SearchModification fixedMod="false" massDelta="324.105652" residues="R">
          <cvParam cvRef="MS" accession="MS:1001460" name="unknown modification" value="Hex_2_" />
        </SearchModification>`

**Comment by FarmGeek4Life** [comment]
The next release should fix this problem; also, thinking about the code I changed yesterday, using "Hex_2_" wouldn't work, because the first thing the code did was remove leading and trailing underscores... The next release will have a check for the name as an exact match, as it appears in the UniMod database.

**Comment by FarmGeek4Life** [comment]
The new [Latest Release](https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/releases/latest ) of 1.0.6510 should take care of this issue.
