### ISSUE TITLE
.param/.mzid file does not include activation method

### ISSUE THREAD

**Issue by liv-acollins** [PNNL-Comp-Mass-Spec/Informed-Proteomics#6]
The .param file appears not to shown the specified -act which was specified, likewise as far as I can see it also isn't shown in the .mzid file.
It would handy specifying it both of these for results validation purposes. Certainly would be good to know what was actually chosen when the default -act 6 is used.

**Comment by FarmGeek4Life** [comment]
Outputting what the user supplied to the .param file and to the "search params" section in the mzid is easy, but outputting what was actually chosen when -act 6 is used is harder, and not possible in the .params file; -act 6 means that the activation method used is determined by the instrument data for each spectrum, so for a file with CID and HCD spectra, each spectrum is scored appropriately according to the activation method used when it was acquired; using a -act that is not 6 overrides this behavior, meaning that, for example, a CID spectra would be scored as if it was HCD. MS-GF+ uses this same behavior, and outputs the "Assumed Dissociation Method" in each SpectrumIdentificationResult, which is what I would prefer to do in this case as well.

**Comment by liv-acollins** [comment]
-act option in .params seems fine. Just handy to verify that what was specified was what was generated.
Likewise, the additional info in the .mzid would be useful.

**Comment by FarmGeek4Life** [comment]
The new [Latest Release](https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/releases/latest ) of 1.0.6510 includes the specified activation method in the .param file and .mzid file.
