### ISSUE TITLE
MSPathFinderT.exe crash 

### ISSUE THREAD

**Issue by somakray** [PNNL-Comp-Mass-Spec/Informed-Proteomics#7]
Hello,

MSPathFinderT.exe crashes issuing the following error:
what could have gone wrong?

```
Total Progress: 94.97%, 2d 14h 45.49m elapsed, Current Task:
Collected candidate matches: 0
Decoy database search elapsed Time: 109057.9 sec
Calculating spectral E-values for decoy-spectrum matches
Estimated matched sequences: 0
Decoy-spectrum match E-value calculation elapsed Time: 0.0 sec
Error computing FDR: Cannot compute FDR Scores; target file is empty
Error processing Frac4_140kR_01.raw: Cannot compute FDR Scores; target file is empty
```

**Comment by FarmGeek4Life** [comment]
It is saying that for some reason, it did not find any target database matches; is the _IcTarget.tsv file empty, or only have headers?

**Comment by somakray** [comment]
Yes, the '_IcTarget.tsv' contains only the headers. Maybe I should re-run with changed parameters in MSPathFinderT.exe to get some hits

**Comment by FarmGeek4Life** [comment]
That error message has now been changed to say ```Error computing FDR: Cannot compute FDR Scores; target results file is empty``` to make it more clear that it is referring to the file containing the target search results.
